-
  hosts: localhost
  tasks: 
      - name: Install Packages
        yum: 
          name: "httpd"
      -name: Start Apache Server
       service: 
          name: httpd
          state: started
          enabled: True
      -name: Deploy Website
       copy:
         src: index.html
         dest: /var/www/html/
-
